"""Initial migration

Revision ID: 24bd0b03aeef
Revises: 
Create Date: 2026-05-19 00:50:31.709946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bd0b03aeef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('gender_code', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('years_old', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('passport_num', sa.String(), nullable=True),
    sa.Column('passport_serial', sa.String(), nullable=True),
    sa.Column('passport_number', sa.Integer(), nullable=True),
    sa.Column('passport_code', sa.String(), nullable=True),
    sa.Column('passport_issued', sa.String(), nullable=True),
    sa.Column('passport_date', sa.String(), nullable=True),
    sa.Column('inn_fiz', sa.String(), nullable=True),
    sa.Column('inn_ur', sa.String(), nullable=True),
    sa.Column('snils', sa.String(), nullable=True),
    sa.Column('oms', sa.BigInteger(), nullable=True),
    sa.Column('ogrn', sa.String(), nullable=True),
    sa.Column('kpp', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('address_reg', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('house', sa.Integer(), nullable=True),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.Column('bank_bik', sa.BigInteger(), nullable=True),
    sa.Column('bank_corr', sa.String(), nullable=True),
    sa.Column('bank_inn', sa.BigInteger(), nullable=True),
    sa.Column('bank_kpp', sa.Integer(), nullable=True),
    sa.Column('bank_num', sa.String(), nullable=True),
    sa.Column('bank_client', sa.String(), nullable=True),
    sa.Column('bank_card', sa.String(), nullable=True),
    sa.Column('bank_date', sa.String(), nullable=True),
    sa.Column('bank_cvc', sa.Integer(), nullable=True),
    sa.Column('edu_specialty', sa.String(), nullable=True),
    sa.Column('edu_program', sa.String(), nullable=True),
    sa.Column('edu_name', sa.String(), nullable=True),
    sa.Column('edu_doc_num', sa.String(), nullable=True),
    sa.Column('edu_reg_number', sa.String(), nullable=True),
    sa.Column('edu_year', sa.Integer(), nullable=True),
    sa.Column('car_brand', sa.String(), nullable=True),
    sa.Column('car_model', sa.String(), nullable=True),
    sa.Column('car_year', sa.Integer(), nullable=True),
    sa.Column('car_color', sa.String(), nullable=True),
    sa.Column('car_number', sa.String(), nullable=True),
    sa.Column('car_vin', sa.String(), nullable=True),
    sa.Column('car_sts', sa.String(), nullable=True),
    sa.Column('car_sts_date', sa.String(), nullable=True),
    sa.Column('car_pts', sa.String(), nullable=True),
    sa.Column('car_pts_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
